---
abstract: 'UAV::Pilot driver for the Parrot AR.Drone'
author:
  - 'Timm Murray <tmurray@wumpus-cave.net>'
build_requires: {}
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: UAV-Pilot-ARDrone
provides:
  UAV::Pilot::ARDrone:
    file: lib/UAV/Pilot/ARDrone.pm
    version: 0.1
  UAV::Pilot::ARDrone::Control:
    file: lib/UAV/Pilot/ARDrone/Control.pm
    version: 0
  UAV::Pilot::ARDrone::Control::Event:
    file: lib/UAV/Pilot/ARDrone/Control/Event.pm
    version: 0
  UAV::Pilot::ARDrone::Driver:
    file: lib/UAV/Pilot/ARDrone/Driver.pm
    version: 0
  UAV::Pilot::ARDrone::Driver::Mock:
    file: lib/UAV/Pilot/ARDrone/Driver/Mock.pm
    version: 0
  UAV::Pilot::ARDrone::NavPacket:
    file: lib/UAV/Pilot/ARDrone/NavPacket.pm
    version: 0
  UAV::Pilot::ARDrone::SDLNavOutput:
    file: lib/UAV/Pilot/ARDrone/SDLNavOutput.pm
    version: 0
  UAV::Pilot::ARDrone::Video:
    file: lib/UAV/Pilot/ARDrone/Video.pm
    version: 0
  UAV::Pilot::ARDrone::Video::Mock:
    file: lib/UAV/Pilot/ARDrone/Video/Mock.pm
    version: 0
recommends:
  UAV::Pilot::SDL: 0
  UAV::Pilot::Video::Ffmpeg: 0
requires:
  AnyEvent: 0
  AnyEvent::ReadLine::Gnu: 0
  File::ShareDir: 1.00
  IO::Socket::Multicast: 0
  Math::Trig: 0
  Moose: 0
  MooseX::Event: 0
  String::CRC32: 0
  Test::More: 0
  UAV::Pilot: 0.9
  namespace::autoclean: 0
  perl: v5.14.0
resources:
  license: http://opensource.org/licenses/bsd-license.php
  repository: https://github.com/frezik/UAV-Pilot-ARDrone
version: 0.1
